version: 2
updates:
  - package-ecosystem: ["npm", "github-actions"] # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "friday"
    groups: 
      all-packages:
        patterns: 
          - "*"